import { Outfit } from "next/font/google";
import "./globals.css";
import { Header } from "./_componets/Header";

const outfit = Outfit({ subsets: ["latin"] })

export const metadata = {
  title: "Coffee Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-stone-200 ${outfit.className} text-orange-900`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
