'use client'
import { Outfit } from "next/font/google";
import "./globals.css";
import { Header } from "./_componets/Header";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCartContext";
import { useState } from "react";

const outfit = Outfit({ subsets: ["latin"] })

// export const metadata = {
//   title: "Coffee Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname()
  const [updateCart, setUpdateCart] = useState(false)
  const showHeader = (params === '/sign-in' || params === '/create-account') ? false : true

  return (
    <html lang="en" className="h-full">
      <link rel="shortcut icon" href="/coffee-cup.png" type="image/x-icon" />
      <title>Coffee Store</title>
      <body className={`bg-stone-200 ${outfit.className} text-orange-900 h-full`}>
        <UpdateCartContext.Provider value={{updateCart, setUpdateCart}}>
          {showHeader && <Header />}
          {children}
          <Toaster />
        </UpdateCartContext.Provider>
      </body>
    </html>
  );
}
