'use client'
import { Outfit } from "next/font/google";
import "./globals.css";
import { Header } from "./_componets/Header";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";

const outfit = Outfit({ subsets: ["latin"] })

// export const metadata = {
//   title: "Coffee Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname()
  const showHeader = (params === '/sign-in' || params === '/create-account') ? false : true

  return (
    <html lang="en" className="h-full">
      <link rel="shortcut icon" href="/coffee-cup.png" type="image/x-icon" />
      <title>Coffee Store</title>
      <body className={`bg-stone-200 ${outfit.className} text-orange-900 h-full`}>
        {showHeader && <Header />}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
